import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { handler } from '../../helpers/FetchData';
//const productsList = require('../../data/data.json');


export default function products({products}) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Products Catalog</h1>
        <p>Listing all of the products</p>
        {products.map(product => (
          <>
            <Link href = {`/products/${product.id}`}>
            <h3>{product.title}</h3>
            </Link>
            <h4>{product.price}</h4>
          </>
      ))
      }
    </main>
    </div>
  )
}

export async function getServerSideProps() {
  const productsList = await handler('http://localhost:3000/api/products');  
  return {
    props:{
      products : productsList
    }
  }
}
