import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
const productsList = require('../../data/data.json');


export default function products() {
  console.log(productsList);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Products Catalog</h1>
        <p>Listing all of the products</p>
        {productsList.map(product => (
          <>
            <Link href = {`/products/${product.id}`}>
            <h3>{product.title}</h3>
            </Link>
            <h4>{product.price}</h4>
          </>
      ))
      }
    </main>
    <footer>
        <p>This is Footer</p>
      </footer>
    </div>
  )
}
